version: '3.7'

services:
  rabbitmq:
    build: ./rabbitmq
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - adidas-network
      - intertop-network
  adidas:
    build: manufactures/adidas
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - "8001:8080"
    depends_on:
      - rabbitmq
    networks:
      - adidas-network
  intertop:
    build: distributors/intertop
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - "8101:8080"
    depends_on:
      - rabbitmq
    networks:
      - intertop-network
networks:
  adidas-network:
    driver: "bridge"
  intertop-network:
    driver: "bridge"