/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.romanko.rapid.clothes.manufacturer.adidas;

import org.junit.Test;

public class ApplicationTest {
    @Test
    public void test() {
    }
}
